#!/bin/bash
set -e

# tails persistence location
TAILSDATA=/live/persistence/TailsData_unlocked
# where we cache files for use with with tails-clone-persistent
SKEL=/var/cache/frith

# only do postinst when installed on Tails
# this creates a sensible persistent volume skeleton that frith uses when
# cloning itself onto a fresh USB disk

if [ -d $TAILSDATA ]; then
	/usr/lib/frith/frith-install $SKEL
fi
