#!/bin/bash
set -e

# tails persistence location
TAILSDATA=/live/persistence/TailsData_unlocked
# where we cache files for use with with tails-clone-persistent
SKEL=/var/cache/frith
OLDSKEL=/var/lib/frith/skel

# only do postinst when installed on Tails
# this creates a sensible persistent volume skeleton that frith uses when
# cloning itself onto a fresh USB disk

if [ -d $TAILSDATA ]; then
	if [[ ! -d $SKEL ]]; then
		mkdir -p $SKEL
	fi
	/usr/lib/frith/frith-install.sh $SKEL

	# clean up old skel installations
	if [[ -d $OLDSKEL ]]; then
		rm -rf $OLDSKEL
	fi
fi
